sudo: required
dist: trusty
language: cpp

env:
  global:
    - LANG="en_US.UTF-8"
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: USE_CC=gcc-5 USE_CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-5-multilib
            - g++-5
            - g++-5-multilib
            - cmake
            - lcov
        sonarcloud:
          organization: "ark-game"
          token:
            secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="

    - os: linux
      dist: xenial
      sudo: required
      env: USE_CC=gcc-6 USE_CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gcc-6-multilib
            - g++-6
            - g++-6-multilib
            - cmake
            - lcov
        sonarcloud:
          organization: "ark-game"
          token:
            secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="

    - os: linux
      dist: xenial
      sudo: required
      env: USE_CC=gcc-7 USE_CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gcc-7-multilib
            - g++-7
            - g++-7-multilib
            - cmake
            - lcov
        sonarcloud:
          organization: "ark-game"
          token:
            secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="

    - os: linux
      dist: xenial
      sudo: required
      env: USE_CC=gcc-8 USE_CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - gcc-8-multilib
            - g++-8
            - g++-8-multilib
            - cmake
            - lcov
        #sonarcloud
        sonarcloud:
          organization: "ark-game"
          token:
            secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="
    - os: osx
      osx_image: xcode11.2
      addons:
        #sonarcloud
        sonarcloud:
          organization: "ark-game"
          token:
            secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - export CC=$USE_CC ;
  - export CXX=$USE_CXX ;

script:
  - bash ./scripts/travis_compiler.sh
  # If you wanna get more info, please add the argument -X
  - sonar-scanner #-X
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5

after_success:
  - cd build && ctest -j2 -V

cache:
  directories:
    - "$HOME/.sonar/cache"

notifications:
  email:
    - nickyang1988@qq.com
    - 410274624@qq.com
    - loscaz@qq.com
