sudo: required
dist: trusty
language: cpp

branches:
  except:
    - gh-pages

env:
  global:
    - LANG="en_US.UTF-8"
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-5-multilib
            - g++-5
            - g++-5-multilib
            - cmake
            - lcov
        # sonarcloud:
        #   organization: "ark-game"
        #   token:
        #     secure: "$TRAVIS_SONAR_TOKEN"
      env: USE_CC=gcc-5 USE_CXX=g++-5

    - os: linux
      dist: xenial
      sudo: required

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gcc-6-multilib
            - g++-6
            - g++-6-multilib
            - cmake
            - lcov
        #sonarcloud:
        #  organization: "ark-game"
        #  token:
        #    secure: "$TRAVIS_SONAR_TOKEN"
      env: USE_CC=gcc-6 USE_CXX=g++-6

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gcc-7-multilib
            - g++-7
            - g++-7-multilib
            - cmake
            - lcov
        #sonarcloud:
        #  organization: "ark-game"
        #  token:
        #    secure: "$TRAVIS_SONAR_TOKEN"
      env: USE_CC=gcc-7 USE_CXX=g++-7

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - gcc-8-multilib
            - g++-8
            - g++-8-multilib
            - cmake
            - lcov
        # sonarcloud:
        #   organization: "ark-game"
        #   token:
        #     secure: "$TRAVIS_SONAR_TOKEN"
      env: USE_CC=gcc-8 USE_CXX=g++-8

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - gcc-9-multilib
            - g++-9
            - g++-9-multilib
            - cmake
            - lcov
        #sonarcloud:
        #  organization: "ark-game"
        #  token:
        #    secure: "$TRAVIS_SONAR_TOKEN"
      env: USE_CC=gcc-9 USE_CXX=g++-9

    - os: osx
      osx_image: xcode11.2
      #addons:
      #  sonarcloud:
      #    organization: "ark-game"
      #    token:
      #      secure: "$TRAVIS_SONAR_TOKEN"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - export CC=$USE_CC ;
  - export CXX=$USE_CXX ;

script:
  - bash ./scripts/travis_compiler.sh
  # If you wanna get more info, please add the argument -X
  - sonar-scanner #-X
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5

after_success:
  - cd build && ctest -j2 -V

cache:
  directories:
    - "$HOME/.sonar/cache"

notifications:
  email:
    - nickyang1988@qq.com
    - 410274624@qq.com
    - loscaz@qq.com
