version: 2
jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake

    steps:
      - checkout
      - run: 
        name: dep
        command: |
          cd dep
          chmod -R 755 build_dep.sh 
          ./build_dep.sh
          cd ..
      - run: 
        name: build
        command: |
        if [-d "build" ]; then rm -rf build; fi
        mkdir build && cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=OFF ..
        make -j 4
