version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - run:
          name: Update submodule
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Building dependencies
          command: |
            cd dep
            eval ./build_dep.sh
            cd ..
      - run:
          name: Building ARK
          command: |
            if [ -d "build" ]; then rm -rf build; fi
            mkdir build && cd build
            cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=OFF ..
            make -j 4
