version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd dep
            chmod -R 755 build_dep.sh 
            ./build_dep.sh
            cd ..
            if [ -d "build" ]; then rm -rf build; fi
            mkdir build && cd build
            cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=OFF ..
            make -j 4
      - run:
          name: Install sonarqube
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
            unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - run:
          name: Run Sonarqube scanner
          command: |
            export SONARQUBE_TOKEN="2ebf5079c3986356540638f2618cea5aeff345f2"
            eval ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=ark \
            -Dsonar.organization=ark-game \
            -Dsonar.projectName=ARK \
            -Dsonar.sources=../frame/ \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions=**proto** \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectVersion=0.9.4 \
            -Dsonar.login=${SONARQUBE_TOKEN} \
            -Dsonar.password= -X
