---
apiVersion: v1
kind: Service
metadata:
  name: svc-photon-master
  namespace: default
  labels:
    app: photon-master
spec:
  ports:
    - name: game2master
      protocol: TCP
      port: 9002
      targetPort: 9002
  # Headless service
  clusterIP: None
  selector:
    # match pod
    app: photon-master

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-photon-master
  namespace: default
  labels:
    app: photon-master
spec:
  serviceName: "svc-photon-master"
  replicas: 1
  selector:
    matchLabels:
      app: photon-master
  template:
    metadata:
      labels:
        app: photon-master
    spec:
      #      nodeSelector:
      #        type: pvp
      containers:
        - name: photon-master
          image: ark:photon
          imagePullPolicy: Never
          command: ["./bin/app"]
          args:
            - "--busid=1.0.1.${HOSTNAME##*-}"
            - "--name=photon_master"
            - "--app_conf=conf/photon.master.app.conf"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: photon-config
              mountPath: /root/build/conf
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: photon-config
          configMap:
            name: photon-config
