name: Github Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install C++ build wrapper
        run: |
          wget https://binaries.sonarsource.com/CommercialDistribution/sonar-cpp-plugin/build-wrapper-3.11.zip
          unzip build-wrapper-3.11.zip

      - name: Build ARK
        run: |
          # git submodules
          git submodule sync
          git submodule update --init

          # build deps
          cd dep
          chmod -R 755 build_dep.sh
          bash build_dep.sh
          cd ..

          # build ark
          if [ -d "build" ]; then rm -rf build; fi
          mkdir build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=OFF -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON ..

          # make and sonar scanner
          make -j 4
          cd ..
      #- name: SonarCloud Scan
      #  uses: sonarsource/sonarcloud-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
